### ISSUE TITLE
Doesn't run after PR is merged

### ISSUE THREAD

**Issue by rdegges** [jessfraz/branch-cleanup-action#24]
Hey there! I'm new to GitHub actions, so if this is incorrect at all, I apologize!

Here's the issue I'm seeing. I've got a repo that I'd like to use this with. We have a large team working on this project and many people are leaving stale branches around. Anyhow, I went ahead and created a GitHub workflow as defined below (using the new yaml syntax):

```
name: Delete PR Branches on Merge

on: pull_request
jobs:
  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest

    steps:
    - uses: jessfraz/branch-cleanup-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NO_BRANCH_DELETED_EXIT_CODE: 0
```

When I open a new pull request on this repo, this workflow runs and exits without doing anything (since the PR hasn't been merged).

When I merge the PR, however, this workflow doesn't run because it's only running on `pull_request`, and GitHub doesn't consider a merged PR to be a pull_request event, apparently. I wonder if this behavior has changed since this was first built?

Anyhow: I can't seem to find a way to get this to run. Am I way off, or did GitHub change the way that the `pull_request` event works?
